ALTER TABLE posts ALTER COLUMN status ENUM('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'ARCHIVED', 'REJECTED');
ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0 NOT NULL;
ALTER TABLE users ALTER COLUMN role ENUM('USER', 'CONTRIBUTOR', 'ADMIN');
CREATE TABLE IF NOT EXISTS post_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_post_likes_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_likes_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS user_security_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    question_order INT NOT NULL,
    question_text VARCHAR(255) NOT NULL,
    answer_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_security_questions_user_order UNIQUE (user_id, question_order),
    CONSTRAINT chk_user_security_questions_order CHECK (question_order BETWEEN 1 AND 3),
    CONSTRAINT fk_user_security_questions_user FOREIGN KEY (user_id) REFERENCES users(id)
);
