ALTER TABLE posts ALTER COLUMN status ENUM('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'ARCHIVED', 'REJECTED');
ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count INT DEFAULT 0 NOT NULL;
ALTER TABLE users ALTER COLUMN role ENUM('USER', 'CONTRIBUTOR', 'ADMIN');
